CREATE TABLE MOVIE_ACTORS(
    MOVIEID VARCHAR2(50),
    ACTORID VARCHAR2(100),
    ACTORNAME VARCHAR2(150),
    RANKING INTEGER
);

SELECT COUNT(*) FROM MOVIE_ACTORS;

CREATE TABLE MOVIE_COUNTRIES(
    MOVIEID VARCHAR2(50),
    COUNTRY VARCHAR2(100)
);

SELECT COUNT(*) FROM MOVIE_COUNTRIES;

CREATE TABLE MOVIE_DIRECTORS(
    MOVIEID VARCHAR2(50),
    DIRECTORID VARCHAR2(100),
    DIRECTORNAME VARCHAR2(150)
);

SELECT COUNT(*) FROM MOVIE_DIRECTORS;

CREATE TABLE MOVIE_GENRES(
    MOVIEID VARCHAR2(50),
    GENRE VARCHAR2(100)
);

SELECT COUNT(*) FROM MOVIE_GENRES;

CREATE TABLE MOVIE_TAGS(
    MOVIEID VARCHAR2(50),
    TAGID VARCHAR2(100),
    TAGWEIGHT INTEGER
);

SELECT COUNT(*) FROM MOVIE_TAGS;

CREATE TABLE MOVIES(
    MOVIEID VARCHAR2(50),
    TITLE VARCHAR2(200),
    MYEAR INTEGER,
    RTAUDIENCERATING VARCHAR(50),
    RTAUDIENCENUMRATING NUMBER(10)
);

SELECT COUNT(*) FROM MOVIES;

CREATE TABLE TAGS(
    ID VARCHAR2(50) PRIMARY KEY,
    VALUE VARCHAR2(200)
);

SELECT COUNT(*) FROM TAGS;

CREATE TABLE USER_TAGGEDMOVIES(
    USERID VARCHAR2(50),
    MOVIEID VARCHAR2(50),
    TAGID VARCHAR2(100),
    DATE_DAY INTEGER,
    DATE_MONTH INTEGER,
    DATE_YEAR INTEGER,
    DATE_HOUR INTEGER,
    DATE_MINUTE INTEGER,
    DATE_SECOND INTEGER
);

SELECT COUNT(*) FROM USER_TAGGEDMOVIES;
